__title__ = "Medical Chat-Bot"
__description__ = "A Telegram bot that processes medical documents, extracts key information from them, and answers user questions based on the extracted data."
__url__ = "https://github.com/TD555/medical-chatbot"
__version__ = "1.0.0"
__author__ = "Tigran Davtyan"
__author_email__ = "tigran.davtyand@gmail.com"
