version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/data/postgres
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
       - postgres:/data/postgres
      
  telbot:
    image: telegram_bot
    build: 
      context: .

    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}

    env_file: ".env"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy

networks:
  postgres:
    driver: bridge

volumes:
    postgres: