version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=medical_db
      - PGDATA=/data/postgres
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
       - postgres:/data/postgres
      
  telbot:
    image: telegram_bot
    build: 
      context: .

    environment:
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=medical_db
      - # POSTGRES_HOST="postgres"
      - POSTGRES_HOST=localhost
      - # POSTGRES_PORT=5432
      - POSTGRES_PORT=5433

    env_file: ".env"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy

networks:
  postgres:
    driver: bridge

volumes:
    postgres: